apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deployment
  labels:
    app: project-app
spec:
  replicas: 1  # Nombre de pods à exécuter
  selector:
    matchLabels:
      app: project-app
  template:
    metadata:
      labels:
        app: project-app
    spec:
      containers:
      - name: project-container
        image: firasmhalla3099/project-image:latest
        ports:
        - containerPort: 8070   # Mets ici le port exposé par ton image
---
apiVersion: v1
kind: Service
metadata:
  name: project-service
spec:
  selector:
    app: project-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8070
  type: NodePort   # Change en LoadBalancer si tu es sur le cloud